CREATE TABLE polls (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    question VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE poll_responses (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    question_id INTEGER DEFAULT NULL,
    username VARCHAR(50) NOT NULL,
    response CHAR(1) NOT NULL,
    poll_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id)
);