CREATE TABLE polls (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    question VARCHAR(255) NOT NULL,
    option1 VARCHAR(255), 
    option2 VARCHAR(255), 
    option3 VARCHAR(255), 
    option4 VARCHAR(255), 
    PRIMARY KEY (id)
);

CREATE TABLE poll_responses (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    username VARCHAR(50) NOT NULL,
    poll_id INTEGER DEFAULT NULL,
    response CHAR(1) NOT NULL,
    PRIMARY KEY (id), 
    FOREIGN KEY (poll_id) REFERENCES polls(id), 
    FOREIGN KEY (username) REFERENCES users(username)
);